### ISSUE TITLE
Initial Feedback

### ISSUE THREAD

**Issue by SachaG** [mechanical-turk/generator-vulcanjs#3]
Overall, this is really awesome work, I'm impressed! I think this could really help increase Vulcan's adoption. Once this is ready I'll definitely add it to the "getting started" section of the docs. 

A few notes:

- I'm not sure the jsx/js choice is necessary? We could probably pick one for people?
- Similarly, I'm not sure people will know which package they need to depend on when they're creating a new package. I'd probably just depend on `vulcan:core`. 
- The indentation was a bit weird for me. For example:

```
list: {
    name: 'moviesList',
    resolver(root, {
      terms = {}
    }, context, info) {
      let {
        selector,
        options
      } = context.Movies.getParameters(
        terms, {},
        context.currentUser
      );
      return context.Movies.find(selector, options).fetch();
    },
  },
```

 - Routes should probably use `componentName` rather than `component` (to be compatible with component overwriting, if you're creating a theme for example). 
- I wonder if `module` is a good name. Maybe `model` would be better to avoid confusion with ES6 modules?

**Comment by mechanical-turk** [comment]
@SachaG can you elaborate on the componentName thing you mentioned about the routes? I thought that's already what's happening in the code

**Comment by SachaG** [comment]
Oh, maybe I got it wrong? Never mind then.
